### ISSUE TITLE
Can it support alert alignment?

### ISSUE THREAD

**Issue by liujia95** [divadretlaw/CustomAlert#12]
1. I want my CustomAlert to be positioned at the bottom. How can I do this?  : )
2. Is it possible to support closing the Alert by clicking on the background?
Thank you for providing such a useful library, I'm very grateful.

**Comment by divadretlaw** [comment]
> I want my CustomAlert to be positioned at the bottom. How can I do this? : )

Not supported at the moment, but it should be a somewhat easy change. I could probably add `CustomAlertConfiguration.position` with the possible values `.center`, `.bottom` and `.top`

> Is it possible to support closing the Alert by clicking on the background?

Not supported at the moment, but also a rather simple change.

Thank you for your suggestions. I will implement them when I find the time.

**Comment by liujia95** [comment]
Thank you very much! 😊

**Comment by divadretlaw** [comment]
With version `3.1.0` you can provide the following configuration

```swift
.environment(\.customAlertConfiguration, .create { configuration in
    configuration.alignment = .bottom // 1. Align the alert on the bottom
    configuration.dismissOnBackgroundTap = true // 2. Support closing the alert by clicking on the background
})
```

Please let me know if you find any issues regarding this.
