### ISSUE TITLE
Teamd id on pipeline

### ISSUE THREAD

**Issue by pablorodriguezcolbaes** [divadretlaw/CustomAlert#13]
Hi i'm trying to build an app on a pipeline and is giving me this error

Signing for "CustomAlert_CustomAlert" requires a development team. Select a development team in the Signing & Capabilities editor.

and i think id in the demo section of the library.

how can i change the team id on the library?

**Comment by divadretlaw** [comment]
The demo has no team set and will only run on the simulator unless you simply set a team yourself.

Making the demo run on a device is no requirement to use this package.

The package itself has no team, there is no way to set one and it doesn't require one. You can set the team on the demo, just like any other app.
