### ISSUE TITLE
Support Binding Object support for presenting similar to sheet modifier

### ISSUE THREAD

**Issue by cse-ariful** [divadretlaw/CustomAlert#14]
In the current swiftui sheet that has a modifier that take a binding item as parameter and shows the sheet when the parameter is not nil. It would be very helpful if there is a way to use similar  behavior on this library. BTW  Thanks a lot for this awesome and handly library

For example: 

`.sheet(item: $deleteConfirmation, content: { item in     
            })`

**Comment by divadretlaw** [comment]
Good idea. Implemented in `3.2.0`
