### ISSUE TITLE
Latest release bug: pressing on buttons not working all the times

### ISSUE THREAD

**Issue by frogg** [divadretlaw/CustomAlert#17]
I noticed that in the latest release I have to press the buttons really long to get an effect.

If I press them normally, no button callback is triggered, the alert just disappears.

I believe it was introduced by `3.5.0`.

`3.3.0` I am unable to install (does not resolve in Xcode).

On `3.1.0` I am unable to reproduce.

My code to show an alert:

```
.customAlert(confirmationSubtitle, isPresented: $showSelectionConfirmaionAlert) {
   // view code with labels and image
} actions: {
   Button("test 1") {
      // only called when long-pressing button
   }

   Button("test 2") {
      // only called when long-pressing button
   }
}
```

**Comment by frogg** [comment]
Update: I was able to get `3.3.0` installed, on this version I am unable to reproduce the bug either.

So I am pretty sure that the issue has been introduced by the latest version `3.5.0`.

Hope that helps!

**Comment by divadretlaw** [comment]
Thank you for opening this issue. Yeah I moved the gesture to the `AlertButtonStyle`, but that doesn't seem to work properly.

I reverted that change with `3.5.1`

**Comment by frogg** [comment]
Thanks for the quick fix!

**Comment by kasem-sm** [comment]
I'm on 3.7.0 and still facing this issue :/

**Comment by divadretlaw** [comment]
Cannot reproduce the issue with iOS 17.5 (both real device and simulator) using the Demo project on the main branch.

@kasem-sm Maybe a specific iOS version is affected? Could you share some details about your setup on how to reproduce this issue? iOS version, Xcode version, Swift version, Code sample, etc.
Thank you in advance
