### ISSUE TITLE
Failure presenting the alert using a button action from another alert

### ISSUE THREAD

**Issue by murad1981** [divadretlaw/CustomAlert#18]
When I try to show `CustomAlert` when I press on a button from another `CustomAlert` (both are in the same `SwiftUI` view), the second `CustomAlert` does not show up and `XCode` logs this warning in the console:

`[Presentation] Attempt to present a window with key 'CustomAlert' while there is already a window with key 'CustomAlert' presented on the current window scene.`

**Comment by divadretlaw** [comment]
Yeah, this was semi-intentional to prevent showing multiple windows at once, but I don't see a strong reason to keep it, especially if it prevents other flows like your.

Should be fixed in `3.6.1`

**Comment by murad1981** [comment]
yeah there are many cases in which a user needs it, thanks for the effort.
