### ISSUE TITLE
Textfield disabled

### ISSUE THREAD

**Issue by JorgeFrias** [divadretlaw/CustomAlert#2]
When adding a text field on the alert (both body and actions) the field cannot be selected. Am I missing something?

_BTW, amazing project!_

**Comment by divadretlaw** [comment]
Ah yes, thank you for submitting this issue. The Custom Alert will start scrolling if the content is too big to fit, so per default the scrolling is disabled via the `.disabled` modifier but the `Environment` is wrongfully propagated to the content of the alert.

**Comment by divadretlaw** [comment]
Should be fixed with `v2.1.2`

**Comment by JorgeFrias** [comment]
Thanks!
