### ISSUE TITLE
Make AlertDismiss action public.

### ISSUE THREAD

**Issue by cse-ariful** [divadretlaw/CustomAlert#25]
In certain situation where I am showing some custom layout in the alert dialog and from inside the custom layout view. I need to dismiss the alert. However I can access \.alertDismiss environment variable but due to internal access restriction i cannot call this function. 

What I am expecting is making the callAsFunction inside the AlertDismissAction class to be public so that user can call this function from the app.

I Appreciate your time and energy behind this library and this library is very useful for most of the developer as swiftui is missing the function to show custom content in alertDialog

**Comment by divadretlaw** [comment]
Thank you for creating this issue. I'm sure it was some oversight on my end that `callAsFunction` wasn't public.

`AlertDismissAction` is now public and functional to be called from the alert content in `3.8.2`
