### ISSUE TITLE
Buttons no longer working on iOS 18

### ISSUE THREAD

**Issue by XelarCraft** [divadretlaw/CustomAlert#28]
.customAlert("Some Title", isPresented: $showDialog) {
                VStack{
                    SmallTextJustified(name: "Some message body")
                    Spacer()
                }
                
            } actions: {

                Button(role: .destructive) {
                    showDialog = false
                } label: {
                    MediumText(name: "Cancel")
                }

                Button {
                    showDialog = false
                    print("Some message")
                } label: {
                    MediumText(name: "Proceed")
                }
            }

The logic to be executed on button press is no longer getting executed on devices running iOS 18.

**Comment by divadretlaw** [comment]
Thank you for reporting this issue.

I was able to reproduce the issue when using older Xcode versions.

Should be fixed in `4.0.1`

**Comment by gggmmo** [comment]
Hi. This issue happens again on iOS 26, while it is working fine on iOS 18.
