### ISSUE TITLE
EnvironmentObject not working in parent view

### ISSUE THREAD

**Issue by axbeats** [divadretlaw/CustomAlert#4]
Thanks for the effort building a custom alert, much appreciated. 

There is an error when you have an EnvironmentObject in the parent view; when you activate the alert, the parent view loses access to the EnvironmentObject.

Cheers

**Comment by divadretlaw** [comment]
Hello, I'm not quite sure how to reproduce your mentioned issue? The parent view meaning the view with the `.customAlert` or the parent of the view where the `.customAlert` is attached?

Could you maybe provide a minimal reproducible example?

**Comment by axbeats** [comment]
I tried to reproduce the bug in a minimal example, and it all worked. Something else is wrong with my code that makes it lose access to the EnvironmentModel. Sorry to waste your time. Again, thank you very much for your good work!

**Comment by divadretlaw** [comment]
No worries, no time was wasted 😄
