### ISSUE TITLE
backward overlay

### ISSUE THREAD

**Issue by fabricetiennette** [divadretlaw/CustomAlert#6]
Are you thinking of a backward overlay removal option feature in the future ?

**Comment by divadretlaw** [comment]
Not quite sure what you mean by "backward overlay"?

Do you mean the dimmed background when displaying the alert?

In general the custom alert is designed to look and behave exactly like the native alert, but if needed I could add the ability to customize the background, which would also allow it to be removed entirely.

**Comment by mickey4u** [comment]
@divadretlaw Is there a way I can override the background color around the alert content view?

**Comment by divadretlaw** [comment]
@mickey4u you mean like this?

<img src="https://github.com/user-attachments/assets/4665c4d2-d7ae-4163-95bb-4f5f34b57f0d" alt="example" width="270"/>

Then yes

```swift
.customAlert("Title", isPresented: $showAlert){
    Text("Content")
} actions: {
    Button(role: .cancel) {
    } label: {
        Text("OK")
    }
}
.configureCustomAlert { configuration in
    configuration.background = .color(Color.purple.opacity(0.5))
}
```

You can customize the styling via `configureCustomAlert`. If you are missing some customization options you can create an issue or a pull request.

See https://github.com/divadretlaw/CustomAlert/blob/main/Demo/Demo/Alerts/CustomAlerts.swift#L98 for a heavily customized alert example.

**Comment by mickey4u** [comment]
@divadretlaw  no I tried that, so when you embed a custom view into the customAlert it has the default background around the custom view.
<img width="204" alt="Screenshot 2024-09-02 at 23 50 10" src="https://github.com/user-attachments/assets/d40b080b-e167-4d1b-bf0e-e55534d43a45">

**Comment by divadretlaw** [comment]
@mickey4u I don't quite follow, please create a separate issue with some example code if you still have some questions

Here are three configurations with the alert having custom colors. Depending on the configuration you see something of the alert background or not

The alert is configured as follows

- Alert: Yellow background
- Buttons: Green background
- Content: Red Background

| Default | No title, just custom view | No title, alert padding = 0 |
|:-:|:-:|:-:|
| <img width="378" alt="1" src="https://github.com/user-attachments/assets/5a31cf7e-1582-4359-81ac-d55f59890743"> | <img width="378" alt="2" src="https://github.com/user-attachments/assets/2a4f11d0-0c6e-4496-bd2a-2dd8cb5d5e97"> | <img width="378" alt="3" src="https://github.com/user-attachments/assets/2a6cfe2b-e709-4fb6-be06-cc2aace85561"> |
