### ISSUE TITLE
Run multiple times before displaying

### ISSUE THREAD

**Issue by SoggyDirector** [divadretlaw/CustomAlert#8]
When I trigger the alert, It runs 3 times every time. When I click an action button, it is supposed to display an error message. I have to click the action button 2 times before it shows and every time I click that button it runs the alert 2 times instead of 3. I would like to know If I'm doing something wrong.

**Comment by divadretlaw** [comment]
Hello, do you have a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example)? Not quite sure what you mean by "runs the alert multiple times", and without some code its really difficult to see what the error could be.

The `Demo` project in the package should give a good basic idea on how to use this package.
